# Generated by Django 4.0.5 on 2022-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date_to_delivery', models.DateField()),
                ('price_in_usd', models.PositiveIntegerField()),
                ('price_in_rub', models.PositiveIntegerField()),
            ],
        ),
    ]
